# Generated by Django 5.2.11 on 2026-02-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_income_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='accepted_by',
        ),
    ]
